<?php

declare(strict_types=1);

namespace App\Infrastructure\Twig;

use App\Application\AppUrl;
use App\Domain\Activity\Activity;
use App\Domain\Activity\SportType\SportType;
use App\Domain\Image\ImageOrientation;
use App\Domain\Segment\Segment;
use App\Infrastructure\ValueObject\String\RelativeUrl;
use Symfony\Component\HttpFoundation\RequestStack;
use Twig\Attribute\AsTwigFilter;
use Twig\Attribute\AsTwigFunction;

/*
 * OVERRIDDEN UPSTREAM FILE — resync on every image bump.
 *
 * Same as upstream except toRelativeUrl() re-anchors the result on the current
 * request's base URL (see prefixWithRequestBaseUrl below).
 *
 * relativeUrl() builds root-absolute URLs from APP_URL's base path. Under Home
 * Assistant ingress the base path is not in APP_URL at all: it is a per-session
 * /api/hassio_ingress/<token> prefix the supervisor proxy strips and forwards as
 * X-Ingress-Path, which the Caddyfile maps to X-Forwarded-Prefix. APP_URL is
 * only a placeholder (http://localhost:8080), so getBasePath() is null and
 * relativeUrl() emits bare root-absolute paths.
 *
 * Calls that wrap path()/asset() were unaffected — Symfony's URL generator and
 * asset packages already prepend the forwarded prefix — but the literal-path
 * calls were not, and the browser resolved them against the Home Assistant host
 * root instead of the ingress base:
 *
 *   - relativeUrl('/')                     admin "Return to app" / "Back to app"
 *     (templates/html/admin/navigation/top-nav-bar.html.twig,
 *      templates/html/admin/login.html.twig,
 *      templates/html/strava-oauth/not-available-in-file-import-mode.html.twig)
 *     emitted href="/", so the ingress iframe navigated to the HA dashboard —
 *     Home Assistant rendered inside Home Assistant.
 *   - relativeUrl('assets/images/logo.svg'), relativeUrl('js/dist/'),
 *     placeholderImage(), securedImageUrl(), countryIcon() and the admin
 *     "/activities#/activity/<id>.html" deep links pointed at the HA root too.
 *
 * The static build is generated by CLI commands, where there is no request and
 * the prefix is empty, so build output is unchanged (it keeps being re-anchored
 * to "./" by sfs-reconcile-config.sh).
 */
final readonly class UrlTwigExtension
{
    public function __construct(
        private AppUrl $appUrl,
        private StringTwigExtension $stringTwigExtension,
        private SvgsTwigExtension $svgsTwigExtension,
        // Optional so upstream's own UrlTwigExtensionTest, which constructs this
        // class with the three arguments above, keeps working.
        private ?RequestStack $requestStack = null,
    ) {
    }

    #[AsTwigFunction('relativeUrl')]
    public function toRelativeUrl(string $path): string
    {
        return $this->prefixWithRequestBaseUrl(
            RelativeUrl::from($path, $this->appUrl)->toRelativeUrl()
        );
    }

    /**
     * Prepend the current request's base URL (the reverse-proxy prefix from
     * X-Forwarded-Prefix, empty on direct :8080 access and on CLI) unless the
     * URL already carries it, which is the case for the many call sites that
     * pass path()/asset() output through relativeUrl().
     */
    private function prefixWithRequestBaseUrl(string $url): string
    {
        $baseUrl = rtrim($this->requestStack?->getCurrentRequest()?->getBaseUrl() ?? '', '/');
        if ('' === $baseUrl) {
            return $url;
        }
        if ($url === $baseUrl || str_starts_with($url, $baseUrl.'/')) {
            return $url;
        }

        return $baseUrl.$url;
    }

    #[AsTwigFunction('securedImageUrl')]
    public function securedImageUrl(string $imageUrl): string
    {
        $pathRelativeToFiles = ltrim((string) preg_replace('#^/?files/#', '', $imageUrl), '/');

        return $this->toRelativeUrl('secured-image/'.$pathRelativeToFiles);
    }

    #[AsTwigFunction('placeholderImage')]
    public function placeholderImage(?ImageOrientation $imageOrientation = null): string
    {
        if (ImageOrientation::PORTRAIT === $imageOrientation) {
            return $this->toRelativeUrl('/assets/placeholder-portrait.webp');
        }

        return $this->toRelativeUrl('/assets/placeholder.webp');
    }

    #[AsTwigFilter('countryIcon')]
    public function countryIcon(string $countryCode): string
    {
        return $this->toRelativeUrl('/assets/images/flags/'.strtolower($countryCode).'.svg');
    }

    #[AsTwigFilter('activityLink', isSafe: ['html'])]
    public function renderActivityTitleLink(Activity $activity, ?int $ellipses = null, bool $truncate = false): string
    {
        $activityIcon = match (true) {
            !$activity->getSportType()->isVirtualRide() => $this->svgsTwigExtension->svgSportType($activity->getSportType()),
            $activity->isZwiftRide() => $this->svgsTwigExtension->svg('zwift-logo'),
            $activity->isRouvyRide() => $this->svgsTwigExtension->svg('rouvy-logo'),
            $activity->isMyWhooshRide() => $this->svgsTwigExtension->svg('my-whoosh-logo'),
            default => $this->svgsTwigExtension->svgSportType(SportType::RIDE),
        };

        $activityTitle = $activity->getName();

        return sprintf(
            '<a href="#" data-model-content-url="%s" class="flex items-center gap-x-1 font-medium text-blue-600 hover:underline" rel="nofollow">%s<span class="%s">%s</span></a>',
            $this->toRelativeUrl('activity/'.$activity->getId().'.html'),
            $activityIcon,
            $truncate ? 'truncate' : '',
            $ellipses ? $this->stringTwigExtension->doEllipses($activityTitle, $ellipses) : $activityTitle
        );
    }

    #[AsTwigFilter('segmentLink', isSafe: ['html'])]
    public function renderSegmentTitleLink(Segment $segment): string
    {
        $segmentIcon = match (true) {
            !$segment->getSportType()->isVirtualRide() => $this->svgsTwigExtension->svgSportType($segment->getSportType()),
            $segment->isZwiftSegment() => $this->svgsTwigExtension->svg('zwift-logo'),
            $segment->isRouvySegment() => $this->svgsTwigExtension->svg('rouvy-logo'),
            $segment->isMyWhooshSegment() => $this->svgsTwigExtension->svg('my-whoosh-logo'),
            default => $this->svgsTwigExtension->svgSportType(SportType::RIDE),
        };

        $segmentTitle = $segment->getName();

        return sprintf(
            '<a href="#" data-model-content-url="%s" class="flex items-center gap-x-1 font-medium text-blue-600 hover:underline" rel="nofollow">%s<span class="truncate">%s</span></a>',
            $this->toRelativeUrl('segment/'.$segment->getId().'.html'),
            $segmentIcon,
            $this->stringTwigExtension->doEllipses((string) $segmentTitle, 50)
        );
    }
}
